services:

  gateway-service:
    image: sih-gateway-service:2.0.0
    container_name: gateway-service
    build: ./java/gateway-service

    ports:
      - "5001:5001"

    restart: unless-stopped

    environment:
      EUREKA_SERVER_HOST: discovery-service
      EUREKA_SERVER_PORT: 5000
      SPRING_PROFILES_ACTIVE: docker

    depends_on:
      discovery-service:
        condition: service_healthy
      media-service:
        condition: service_healthy
      sms-test-service:
        condition: service_healthy
      sql-service:
        condition: service_healthy
      sms-service:
        condition: service_healthy
      room-service:
        condition: service_healthy

    networks:
      - sih-network


  discovery-service:
    image: sih-discovery-service:1.0.0
    container_name: discovery-service
    build: ./java/discovery-service

    ports:
      - "5000:5000"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

    networks:
      - sih-network

  media-service:
    image: sih-media-service:1.0.17
    container_name: media-service
    build: ./java/media-service

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

    environment:
      EUREKA_SERVER_HOST: discovery-service
      EUREKA_SERVER_PORT: 5000
      SPRING_PROFILES_ACTIVE: docker

    depends_on:
      discovery-service:
        condition: service_healthy

    networks:
      - sih-network

  room-service:
    image: sih-room-service:1.0.20
    container_name: room-service
    build: ./java/room-service

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

    environment:
      EUREKA_SERVER_HOST: discovery-service
      EUREKA_SERVER_PORT: 5000
      SPRING_PROFILES_ACTIVE: docker

    depends_on:
      discovery-service:
        condition: service_healthy

    networks:
      - sih-network


  sql-service:
    image: sih-sql-service:1.0.10
    container_name: sql-service
    build: ./java/sql-service

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

    environment:
      EUREKA_SERVER_HOST: discovery-service
      EUREKA_SERVER_PORT: 5000
      SPRING_PROFILES_ACTIVE: docker

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      RABBITMQ_QUEUE_LOCATION: ${QUEUE}
      RABBITMQ_EXCHANGE_NAME: ${EXCHANGE_KEY}
      RABBITMQ_ROUTING_LOCATION: ${ROUTING_KEY}

    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - sih-network

  sms-test-service:
    image: sms-test-service:1.0.0
    container_name: sms-test-service
    build: ./java/sms-test-service

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

    environment:
      EUREKA_SERVER_HOST: discovery-service
      EUREKA_SERVER_PORT: 5000
      SPRING_PROFILES_ACTIVE: docker
      SMS_DEVICE_IP: ${SMS_DEVICE_IP}
      SMS_DEVICE_PORT: ${SMS_DEVICE_PORT}
      SMS_DEVICE_USERNAME: ${SMS_DEVICE_USERNAME}
      SMS_DEVICE_PASSWORD: ${SMS_DEVICE_PASSWORD}

    depends_on:
      discovery-service:
        condition: service_healthy

    networks:
      - sih-network

  sms-service:
    image: sms-service:1.0.2
    container_name: sms-service
    build: ./java/sms-service

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

    environment:
      EUREKA_SERVER_HOST: discovery-service
      EUREKA_SERVER_PORT: 5000
      SPRING_PROFILES_ACTIVE: docker
      SMS_DEVICE_IP: ${SMS_DEVICE_IP}
      SMS_DEVICE_PORT: ${SMS_DEVICE_PORT}
      SMS_DEVICE_USERNAME: ${SMS_DEVICE_USERNAME}
      SMS_DEVICE_PASSWORD: ${SMS_DEVICE_PASSWORD}

    depends_on:
      discovery-service:
        condition: service_healthy
      sql-service:
        condition: service_healthy

    networks:
      - sih-network

  postgres:
    image: postgres:15.18
    container_name: postgres
    restart: unless-stopped

    ports:
      - "9000:5432"

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - sih-network


  rabbitmq:
    image: rabbitmq:management
    container_name: rmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sih-network


networks:
  sih-network:
    driver: bridge

volumes:
  postgres_data:

