services:
  media-service:
    build: ./java/media-service
    container_name: media-service
    ports:
      - 5001:5001
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTHORITIES_HOST: localhost
      AUTHORITIES_PORT: 5000