spring:
  application:
    name: sql-service

  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5003

db:
  host: xx
  port: xx
  username: xx
  password: xx

